name = "Zaphod"
license = "MIT"
licenselink = "https://github.com/.../.../LICENSE.md"
description = ""
homepage = "http://tenuouscheese.github.io/zaphod/"
tags = ["business", "simple"]
features = ["responsive", "simple"]

[author]
  name = "Nathan S. Stone"
  homepage = "nerdcouture.co.uk"
